[package]
name = "day-10"
version = "0.1.0"
authors = ["Frederic Dumont <fdumontmd@gmail.com>"]
edition = "2018"

[dependencies]
aoc-utils = { path = "../../aoc-utils" }
lazy_static = "1.2.0"
regex = "1.1.0"
