[package]
name = "day-12"
version = "0.1.0"
authors = ["Frederic Dumont <fdumontmd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
anyhow = "1.0.25"
lazy_static = "1.4.0"
