[package]
name = "day23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-utils = { path = "../../aoc-utils" }
anyhow = "1.0.69"

[profile.test]
opt-level = 3

